### ISSUE TITLE
Inconsistent interactions in the python and web 'interactions' data. 

### ISSUE THREAD

**Issue by mgrantpeters** [saezlab/pypath-omnipath#1]
A collaborator and I are having distinct results with an enquiry. 

**How did you access the data?**
On python: db = op.interactions.import_intercell_network(transmitter_params = {"categories":"ligand"}, receiver_params = {"categories": "receptor"})
On web inquiry: 
https://omnipathdb.org/interactions

**Why do you think the data is wrong?**
From my understanding the inquiry op.interactions.import_intercell_network pulls intercell network with ligand and receptor annotation from the interactions data, however there are interactions I detect with this inquiry that are not occurring in the web inquiry of all interactions (which I would have thought was even more comprehensive than the python inquiry). 

**An example of the wrong data**
e.g.: I have a relationship in python inquiry that is not observable in the web interactions inquiry (Source: P52803; Target: P06241)

**What solution you can expect?**
Is there something incorrect in my assumption of the data I am sourcing? Why is it inconsistent across both platforms?

**Comment by boyiguo1** [comment]
Just to add, the said relationship could not be found via the web inquiries
https://omnipathdb.org/interactions/?genesymbols=1&partners=P06241&datasets=omnipath,ligrecextra
https://omnipathdb.org/interactions/?genesymbols=1&partners=P06241&databases=Wang

`Wang` is the database python inquiry shows that contains the said relationship

**Comment by deeenes** [comment]
Hello,

This interaction is in the "pathwayextra" dataset. It will be returned only if this dataset is enabled:

https://omnipathdb.org/interactions/?genesymbols=1&partners=P06241&databases=Wang&datasets=pathwayextra&fields=sources,references&genesymbols=yes&partners=P52803,P06241&source_target=and

The `import_intercell_network` function by default includes all PPI datasets, to override this, use the `include` parameter. More info about the network datasets [here](https://r.omnipathdb.org/articles/bioc_workshop.html#networks).

Best,

Denes

**Comment by mgrantpeters** [comment]
Fantastic - thank you!
